# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'OS to bootrap'
        # Default value if no value is explicitly provided
        default: ubuntu-latest
        # Input has to be provided for the workflow to run
        required: true
  push:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run_on_os:
    # The type of runner that the job will run on
    defaults:
      run:
        shell: bash
        working-directory: scripts
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@master
    - name: Run bootrap
      run: |
        echo "Bootraping in OS ${{ matrix.os }}"
        ./bootstrap
